LOGGING_LEVEL: 'INFO'
LOGGING_FORMAT: '%(asctime)-15s | %(levelname)s | %(filename)s | %(lineno)d: %(message)s'

WEB_HOST: '0.0.0.0'
WEB_PORT: 8007

#DB_URI: "postgresql+asyncpg://postgres:postgres@127.0.0.1:5432/currencies"
DB_URI: "clickhouse://user_monitoring:qwerty123266qwerty@84.23.52.93/db_etl"
